ProgrammingClass4.MvcLesson/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using ProgrammingClass4.MvcLesson.Data;
using ProgrammingClass4.MvcLesson.Models;

namespace ProgrammingClass4.MvcLesson.Controllers
{
    public class ProductTypeController : Controller
    {
        private ApplicationDbContext _dbContext;
        public ProductTypeController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            List<ProductType> productType = _dbContext.ProductType.ToList();//_dbContext fieldi ognutyamb ProductType list@ vercnum enq u dnum enq productTypes popoxakani mej
            //poxancum enq Viewin productTypes@,tvyalner@ poxancecinq View(ProductType) folderin

            return View(productType);
        }
        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductType productType)//save
        {
            if (ModelState.IsValid)
            {
                _dbContext.ProductType.Add(productType);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(productType);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var productType = _dbContext.ProductType.Find(id);

            if (productType != null) 
            {
                return View(productType);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(ProductType productType)//save
        { 
            if (ModelState.IsValid)
            {
                _dbContext.ProductType.Update(productType);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(productType);
        
        }
    }
}

ProgrammingClass4.MvcLesson/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Mvc;
using ProgrammingClass4.MvcLesson.Data;
using ProgrammingClass4.MvcLesson.Models;

namespace ProgrammingClass4.MvcLesson.Controllers
{
    public class ProductTypesController1 : Controller
    {
        private ApplicationDbContext _dbContext;
        public ProductTypesController1(ProductTypesController1 dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            List<ProductTypes>productTypes = _dbContext.ProductTypes.ToList();

            return View(productTypes);
        }
    }
}

ProgrammingClass4.MvcLesson/Views/ProductType/Create.cshtml
@model ProductType

<form asp-controller="ProductType" asp-action="Create">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">
            Name
        </label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger">

        </span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label">
            Description
        </label>
        <textarea asp-for="Description" class="form-control">
            Description
        </textarea>
        <span asp-validation-for="Description" class="text-danger">

        </span>
    </div>
    <div>
        <a asp-controller="ProductType" asp-action="Index" class="btn btn-secondary">
            cancel
        </a>
        <button type="submit" class="btn btn-primary">
            Save
        </button>
    </div>
</form>

ProgrammingClass4.MvcLesson/Views/ProductType/Edit.cshtml
@model ProductType 

<form asp-controller="ProductType" asp-action="Edit">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">
            Name
        </label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger">

        </span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label">
            Description
        </label>
        <textarea asp-for="Description" class="form-control">

        </textarea>
        <span asp-validation-for="Description" class="text-danger">

        </span>
    </div>
    <div class="mb-3">
        <a asp-controller="ProductType" asp-action="index" class="btn btn-secondary">
            Cancel
        </a>
        <button type="submit" class="btn btn-primary">
            Save
        </button>
    </div>
</form>

ProgrammingClass4.MvcLesson/Views/ProductType/Index.cshtml
@model List<ProductType> // Model@ nshanakum enq ProductType
@{
    ViewData["Title"] = "ProductType";
}
<div>
    <a asp-controller="ProductType" asp-action="Create" class="btn btn-primary">
        Creat Product type
    </a> 
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Action
            </th>
         
        </tr>
    </thead>
    <tbody>
        @foreach(var productType in Model)//Model@ dynamica iskzbane,bayc verevum iran sarqelenq List<ProductType> tesaki
        {
            <tr>
                <td>
                    @productType.Id
                </td>
                <td>
                    @productType.Name
                </td>
                <td>
                    @productType.Description
                </td>
                <td>
                    <a asp-controller="ProductType" asp-action="Edit" asp-route-id="@productType.Id " class="btn btn-secondary">
                       Edit
                    </a>
                </td>

            </tr> 
        }
    </tbody>
    </table>