ProgrammingClass4.MvcLesson/Controllers/SizesController.cs
using Microsoft.AspNetCore.Mvc;
using ProgrammingClass4.MvcLesson.Data;
using ProgrammingClass4.MvcLesson.Models;

namespace ProgrammingClass4.MvcLesson.Controllers
{
    public class SizesController : Controller
    {
        private ApplicationDbContext _dbContext;

        public SizesController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        
        public IActionResult Index()
        {
           List<Size> sizes = _dbContext.Sizes.ToList();
            return View(sizes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Size size)
        {
           if (ModelState.IsValid)
            {
                _dbContext.Sizes.Add(size);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            } 
            return View(size);
        }   

        public IActionResult Edit(int id)
        {
            var size = _dbContext.Sizes.Find(id);
            if(size!=null)
            {
                return View(size);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(Size size) 
        { 
            if(ModelState.IsValid)
            {
                _dbContext.Sizes.Update(size);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(size);
        
        }

    }
}

ProgrammingClass4.MvcLesson/Views/Sizes/Create.cshtml
@model Size

<h2>
    Create Size
</h2>
<form asp-controller="Sizes" asp-action="Create">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">
            Name
        </label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3"> 
        <label asp-for="Description" class="form-label">
            Description
        </label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">
        Save
    </button>

</form>

ProgrammingClass4.MvcLesson/Views/Sizes/Edit.cshtml
@model Size
<h2>
    Edit
</h2>
<form asp-controller="Sizes" asp-action="Edit">
    <div class="mb-3">
        <label asp-for="Id" class="form-label">
            Id
        </label>
        <input asp-for="Id" class="form-control" readonly />
    </div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">
            Name
        </label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label">
            Description
        </label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <button class="btn btn-primary">
        Save
    </button>
</form>

ProgrammingClass4.MvcLesson/Views/Sizes/Index.cshtml
@model List<Size>
@{
    ViewData["Title"] = "Sizes";
}
<a class="btn btn-primary" asp-controller="Sizes" asp-action="Create">
    Create Size
</a>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var size in Model)
        {
            <tr>
                <td>
                    @size.Id
                </td>
                <td>
                    @size.Name
                </td>
                <td>
                    @size.Description
                </td>
                <td>
                    <a asp-controller="Sizes" asp-action="Edit" asp-route-id="@size.Id" class="btn btn-secondary">
                        Edit
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>