ProgrammingClass4.MvcLesson/Models/ShoppingCartColor.cs
namespace ProgrammingClass4.MvcLesson.Models
{
    public class ShoppingCartColor
    {
        public int ShoppingCartId { get; set; }
        public ShoppingCart ShoppingCart { get; set; }

        public int ColorId { get; set; }
        public Color Color { get; set; }
   
    }
}

ProgrammingClass4.MvcLesson/ViewModels/ShoppingCartColorViewModel.cs
using ProgrammingClass4.MvcLesson.Models;

namespace ProgrammingClass4.MvcLesson.ViewModels
{
    public class ShoppingCartColorViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public List<Color>? Colors { get; set; }
        public List<ShoppingCartColor>? ShoppingCartColors { get; set; }
        public ShoppingCartColor ShoppingCartColor { get; set; }
        public Product Product { get; set; }
        public int ColorId { get; set; }
        public int Id { get; set; }
        public string SelectedColorName { get; set; }
        public int ProductId { get; set; }
    }
}

ProgrammingClass4.MvcLesson/Controllers/ShoppingCartColorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgrammingClass4.MvcLesson.Data;
using ProgrammingClass4.MvcLesson.Data.Migrations;
using ProgrammingClass4.MvcLesson.Models;
using ProgrammingClass4.MvcLesson.ViewModels;

namespace ProgrammingClass4.MvcLesson.Controllers
{
    
    public class ShoppingCartColorsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public ShoppingCartColorsController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index(int shoppingCartId)
        {
            var shoppingCart = _dbContext.ShoppingCarts
                .Include(cart => cart.Product)
                .FirstOrDefault(cart => cart.Id == shoppingCartId);

            if (shoppingCart == null)
            {
                return NotFound();
            }
            shoppingCart.Product.ImageUrl = $"/images/products/{shoppingCart.Product.Name.Replace(" ", "-").ToLower()}.jpg";
            
            var productColors = _dbContext.ProductColors
                .Where(pc => pc.ProductId == shoppingCart.ProductId)
                .Include(pc => pc.Color)
                .Select(pc => pc.Color)
                .ToList();

            var shoppingCartColors = _dbContext
                .ShoppingCartColors
                .Include(shoppingCartColor => shoppingCartColor.Color)
                .Where(shoppingCartColor => shoppingCartColor.ShoppingCartId == shoppingCartId)
                .ToList();

            var shoppingCartColorViewModel = new ShoppingCartColorViewModel
            {
                ShoppingCart = shoppingCart,
                Colors = productColors,
                ShoppingCartColors = shoppingCartColors,
            };

            return View(shoppingCartColorViewModel);
        }

        [HttpPost]
        public IActionResult Create(ShoppingCartColorViewModel shoppingCartColorViewModel)
        {
            var existingColor = _dbContext.ShoppingCartColors
                 .FirstOrDefault(s => s.ShoppingCartId == shoppingCartColorViewModel.ShoppingCartColor.ShoppingCartId);

            if (existingColor != null) 
            {
                return RedirectToAction("Index", new { shoppingCartId = shoppingCartColorViewModel.ShoppingCartColor.ShoppingCartId });
            }

            _dbContext.ShoppingCartColors.Add(shoppingCartColorViewModel.ShoppingCartColor);
            _dbContext.SaveChanges();

            return RedirectToAction("Index", new {shoppingCartId = shoppingCartColorViewModel.ShoppingCartColor.ShoppingCartId });
        }

        [HttpPost]
        public IActionResult RemoveItem(int shoppingCartId, int colorId)
        {
            var shoppingCartColor = _dbContext.ShoppingCartColors
                .FirstOrDefault(s => s.ShoppingCartId == shoppingCartId && s.ColorId == colorId );

            if (shoppingCartColor != null)
            {
                _dbContext.ShoppingCartColors.Remove(shoppingCartColor);
                _dbContext.SaveChanges();
            }

            return RedirectToAction("Index", new { shoppingCartId });
        }
    }
}

ProgrammingClass4.MvcLesson/Views/ShoppingCartColors/Index.cshtml
@model ShoppingCartColorViewModel

<div class="shopping-cart-container mb-3">
    <h1>
        @Model.ShoppingCart.Product.Name Colors
    </h1>
</div>
<div class="mb-3">
    <h1>
        <img class="image-size" src="@Model.ShoppingCart.Product.ImageUrl" alt=" @Model.ShoppingCart.Product.Name" />
    </h1>
</div>

<form asp-controller="ShoppingCartColors" asp-action="Create">
    <input type="hidden" name="ShoppingCartColor.ShoppingCartId" value="@Model.ShoppingCart.Id" />
    <div class="mb-3">
        <label for="color-id" class="form-label mb-3">
            <h2>
                Select  Color
            </h2>
        </label>
        <div class="input-group">
            <select id="color-id" name="ShoppingCartColor.ColorId" class="form-control">
                <option> -- Please Select--</option>
                @foreach (var color in Model.Colors)
                {
                    <option value="@color.Id">
                        @color.Name
                    </option>
                }
            </select>
            <button class="btn btn-primary">
                Save
            </button>
            
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var shoppingCartColor in Model.ShoppingCartColors)
        {
            <tr>
                <td>
                    @shoppingCartColor.Color.Name
                </td>
                <td>
                    <form asp-controller="ShoppingCartColors" asp-action="RemoveItem">
                        <input type="hidden" name="shoppingCartId" value="@shoppingCartColor.ShoppingCartId" />
                        <input type="hidden" name="colorId" value="@shoppingCartColor.ColorId" />
                        <button type="submit" class="btn btn-primary">
                            Remove
                        </button>
                    </form>

                </td>
            </tr>
        }
    </tbody>

</table>