ProgrammingClass4.MvcLesson/Models/Color.cs
using System.ComponentModel.DataAnnotations;

namespace ProgrammingClass4.MvcLesson.Models
{
    public class Color
    {
        [Key]
        public int Id { get; set; }
        
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        
        [StringLength(100)]
        public string Description { get; set; }
    }
}

ProgrammingClass4.MvcLesson/Controllers/ColorsController.cs
using Microsoft.AspNetCore.Mvc;
using ProgrammingClass4.MvcLesson.Data;
using ProgrammingClass4.MvcLesson.Models;

namespace ProgrammingClass4.MvcLesson.Controllers
{
    public class ColorsController : Controller
    {

        private ApplicationDbContext _dbContext;

        public ColorsController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        
        public IActionResult Index()
        {
            var colors = _dbContext.Colors.ToList();
            return View(colors);
        }

        public IActionResult Create() 
        { 
            return View();  
        }

        [HttpPost]
        public IActionResult Create(Color color) 
        { 
            if(ModelState.IsValid)
            {
                _dbContext.Colors.Add(color);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }   
            return View(color);
        }

        public IActionResult Edit(int id)
        {
            var color = _dbContext.Colors.Find(id);
            if(color != null)
            {
                return View(color);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(Color color)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Colors.Update(color);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(color);
        }
   
    }
}

ProgrammingClass4.MvcLesson/Views/Colors/Create.cshtml
@model Color

<h2>
    Create Color
</h2>
<form asp-controller="Colors" asp-action="Create">
    <div class=" mb-3">
        <label asp-for="Name" class="form-label">
            Name
        </label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label">
            Description
        </label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">
        Save
    </button>
</form>

ProgrammingClass4.MvcLesson/Views/Colors/Edit.cshtml
@model Color

<h2>
    Edit
</h2>
<form asp-controller="Colors" asp-action="Edit">
    <div class=" mb-3">
        <label asp-for="Id" class="form-label">
            Id
        </label>
        <input asp-for="Id" class="form-control" readonly />
    </div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">
            Name
        </label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label">
            Description
        </label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <button class="btn btn-primary">
        Save
    </button>
</form>

ProgrammingClass4.MvcLesson/Views/Colors/Index.cshtml
@model List<Color>

@{
    ViewData["title"] = "Colors";
}

<a class="btn btn-primary" asp-controller="Colors" asp-action="Create">
    Create Color
</a>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var color in Model)
        {
            <tr>
                <td>
                    @color.Id
                </td>
                <td>
                    @color.Name
                </td>
                <td>
                    @color.Description
                </td>
                <td>
                    <a asp-controller="Colors" asp-action="Edit" asp-route-id="@color.Id" class="btn btn-secondary">
                        Edit
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>